when:
  - branch: main
    event: push
  - event: tag
  
steps:
  - name: deploy
    image: alpine
    commands:
      - apk add mkdocs
      - mkdocs build -d /mnt/caddy-sites/docs.techtransthai.org/
    volumes:
      - /media/core/Data1/Apps/caddy/sites:/mnt/caddy-sites